import { spawn } from 'node:child_process';
import { cp, mkdtemp, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const uiDir = resolve(scriptDir, '..');
const defaultPicoHtmlDir = resolve(uiDir, '../../../PicoServer/PicoServer/HTTP Server/HTML');
const picoHtmlDir = resolve(process.env.PICO_HTML_DIR ?? defaultPicoHtmlDir);
const buildDir = await mkdtemp(join(tmpdir(), 'llama-ui-pico-'));
const PICO_GUIDE = `
<!--
  This is the Pico Server build of the frontend.
  It is automatically generated by npm run build:pico.
  Do not edit this file directly.
-->
`.trim();

async function assertDirectory(path, label) {
	try {
		if (!(await stat(path)).isDirectory()) throw new Error();
	} catch {
		throw new Error(`${label} does not exist: ${path}`);
	}
}

function run(command, args, options) {
	return new Promise((resolvePromise, reject) => {
		const child = spawn(command, args, { stdio: 'inherit', ...options });

		child.once('error', reject);
		child.once('exit', (code, signal) => {
			if (code === 0) {
				resolvePromise();

				return;
			}

			reject(new Error(`${command} failed (${signal ?? `exit ${code}`})`));
		});
	});
}

function dataUrl(content, mimeType) {
	return `data:${mimeType};base64,${content.toString('base64')}`;
}

async function makeStandaloneHtml() {
	let html = await readFile(join(buildDir, 'index.html'), 'utf8');

	const favicon = await readFile(join(uiDir, 'static/favicon.svg'));

	html = html
		.replace(/\s*<link[^>]+rel="(?:apple-touch-icon|manifest)"[^>]*>/g, '')
		.replace(/\s*<link[^>]+rel="apple-touch-startup-image"[^>]*>/g, '')
		.replace(/\s*<link[^>]+rel="icon"[^>]*>/g, '')
		.replace(
			'</head>',
			`\n\t\t<link rel="icon" href="${dataUrl(favicon, 'image/svg+xml')}" />\n\t</head>`
		);

	const localIcons = [
		['/recommended-mcp/exa.ico', 'image/x-icon'],
		['/recommended-mcp/github-light.png', 'image/png'],
		['/recommended-mcp/github-dark.png', 'image/png'],
		['/recommended-mcp/context7.png', 'image/png'],
		['/recommended-mcp/huggingface.ico', 'image/x-icon']
	];

	for (const [assetPath, mimeType] of localIcons) {
		const content = await readFile(join(uiDir, 'static', assetPath));

		html = html.replaceAll(assetPath, dataUrl(content, mimeType));
	}

	const externalAssets = [
		...html.matchAll(/<(?:link|script)[^>]+(?:href|src)="(?!data:|https?:|#)([^"]+)"/g)
	];

	if (externalAssets.length > 0) {
		throw new Error(
			`Pico build still contains external page assets: ${externalAssets.map((match) => match[1]).join(', ')}`
		);
	}

	return `${PICO_GUIDE}\n${html.replaceAll('\r', '')}`;
}

async function replaceLocales() {
	const source = join(buildDir, 'locales');
	const temporaryDestination = join(picoHtmlDir, `.locales-${process.pid}`);
	const destination = join(picoHtmlDir, 'locales');

	await rm(temporaryDestination, { force: true, recursive: true });
	await cp(source, temporaryDestination, { recursive: true });
	await rm(destination, { force: true, recursive: true });
	await rename(temporaryDestination, destination);
}

try {
	await assertDirectory(picoHtmlDir, 'Pico HTML directory');
	await run('npm', ['run', 'build:vite'], {
		cwd: uiDir,
		env: {
			...process.env,
			LLAMA_UI_BUNDLE_STRATEGY: 'inline',
			LLAMA_UI_OUT_DIR: buildDir,
			LLAMA_UI_PICO_BUILD: '1'
		}
	});

	const html = await makeStandaloneHtml();
	const gzip = gzipSync(Buffer.from(html), { level: 9, mtime: 0 });
	const temporaryGzip = join(picoHtmlDir, `.index.html.gz-${process.pid}`);

	// Keep gzip output deterministic across platforms.
	gzip[4] = 0;
	gzip[5] = 0;
	gzip[6] = 0;
	gzip[7] = 0;
	gzip[9] = 0;

	await writeFile(temporaryGzip, gzip);
	await rename(temporaryGzip, join(picoHtmlDir, 'index.html.gz'));
	await replaceLocales();

	await rm(join(picoHtmlDir, '_app'), { force: true, recursive: true });
	await rm(join(picoHtmlDir, 'index.html'), { force: true });
	await rm(join(picoHtmlDir, 'favicon.svg'), { force: true });

	console.log(`Pico UI written to ${picoHtmlDir}`);
	console.log(`index.html.gz: ${Math.ceil(gzip.byteLength / 1024)} KiB`);
} finally {
	await rm(buildDir, { force: true, recursive: true });
}
